# Playbook Ansible pentru rularea platformei Docker folosind docker-compose.
- name: Run docker-compose on remote machine
  hosts: monitoring_server
  become: yes
  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy project
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../.."
        dest: /home/ansible_user/platforma-monitorizare/
        recursive: yes

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ansible_user/platforma-monitorizare/docker

